/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniTestDGZ_CallNativeC */

#ifndef _Included_com_example_jniTestDGZ_CallNativeC
#define _Included_com_example_jniTestDGZ_CallNativeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniTestDGZ_CallNativeC
 * Method:    encryption
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_example_jniTestDGZ_CallNativeC_encryption
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
